on: [ push, pull_request ]
name: Main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Composer install
        run: composer install
      - name: Lint
        run: composer run lint
  cs-fixer:
    needs: lint
    name: PHP-CS-Fixer
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Phplint
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style
